### ISSUE TITLE
`readdir` doesn't account for nested mount points

### ISSUE THREAD

**Issue by konsumer** [zen-fs/core#127] opened 2024-11-04 20:44 UTC
I have a few issues with `readdir` mentioned at #124 

I made a [minimal tester](https://github.com/konsumer/zen-list-recursive) ([demo](http://konsumer.js.org/zen-list-recursive/)).

At first, we thought it was an issue with just `recursive` option, but it seems to not be working, as expected, in a few cases. 

```js
import { configure, fs as fsOrig } from '@zenfs/core'
import { Zip } from '@zenfs/zip'

const fs = fsOrig.promises

const data = await fetch('example-fake-zip-file-1mb.zip').then((r) => r.arrayBuffer())

await configure({
  mounts: {
    '/zip': { backend: Zip, data },
    '/mnt/zip': { backend: Zip, data },
    '/very/deep/structure/zip': { backend: Zip, data }
  }
})

console.log('non-recursive list of /mnt/zip')
console.log(await fs.readdir('/mnt/zip'))
// works ok

console.log('non-recursive list of /very/deep/structure/zip')
console.log(await fs.readdir('/very/deep/structure/zip'))
// works ok

console.log('non-recursive list of /')
console.log(await fs.readdir('/'))
// incorrectly outputs only ['zip']

console.log('recursive list of /')
console.log(await fs.readdir('/', { recursive: true }))
// throws error about /zip missing
```

Normally, this is the sort of thing I would catch with tests, but the `readdir` test does not seem to be catching the issue. Maybe it's something with zip/web, specifically?

**Comment by konsumer** [comment] 2024-11-04 21:05
It could be related to needing to make the directories first, but there are still other issues.

I made a test like this:

```js
// must make dirs that are mounted
await fs.mkdirSync('/mnt/test', { recursive: true })
await fs.mkdirSync('/deep/stuff/here', { recursive: true })
await fs.mkdirSync('/top')

await configure({
	mounts: {
		'/mnt/tester': InMemory,
		'/deep/stuff/here': InMemory,
		'/top': InMemory
	}
})

test('readdir a mounted dir recursively', () => {
  console.log(fs.readdirSync('/', {recursive: true}));
});
```
and got ```
 ✖ readdir a mounted dir recursively (1.79675ms)
    Error: ENOENT: No such file or directory, '/mnt/test/er
```

so something very strange is happening with path.

**Comment by konsumer** [comment] 2024-11-04 21:38
Another inconsistency is that `console.log(await fs.readdir('/very/deep/structure/zip'))` [does work](https://github.com/konsumer/zen-list-recursive/blob/main/docs/demo.js#L25C1-L25C58). If the mount is failing, it should error.

**Comment by james-pre** [comment] 2024-11-04 22:45
@konsumer, while the problem is real, the cause is different.

When `readdir` is called, it artificially adds in the mounts. This was just a simpler way to handle things. The handling of it does not account for recursive `readdir`s, which is why you are missing the directories when doing a `readdir` on a non-direct parent of a mount point.

I'll look into proper handling of this. We will use the same approach as Linux: having a mount point be on an existing directory. This will fix this problem, in addition to making other logic easier to handle.

**Comment by konsumer** [comment] 2024-11-04 22:57
ah, and the top-level stuff was probly working because it does not implement recursive. So, another solution would be to make those "artificially adds in the mounts" calls recursive, so it creates the deep tree, and no need to mkdir, first.

**Comment by james-pre** [comment] 2024-11-04 23:02
I'm going to go with the Linux approach of just having actual directories at the mount points.

**Comment by konsumer** [comment] 2024-11-04 23:13
I am happy to help, if you like. 1 thing to note is that the docs will also need to be updated on a few sub-projects, since they leverage this behavior (for example the readme here talks about `/mnt/zip`, and the other things in examples do not create directories first.)

**Comment by james-pre** [comment] 2024-11-04 23:33
Directories will need to be automatically created for backward compatibility

**Comment by james-pre** [comment] 2024-11-05 17:16
The new tests are passing, can I close this issue @konsumer?

**Closed** 2024-11-05 19:38 UTC
Labels: bug
