### ISSUE TITLE
Overlay with Fetch/IndexedDB backend issue

### ISSUE THREAD

**Issue by terryluan12** [zen-fs/core#78] opened 2024-06-13 21:35 UTC
Hi, 

I'm using zenfs to implement an Overlay Filesystem with a Fetch/IndexedDB readable/writable backend. I am having a bit of trouble using the filesystem/understanding the documentation.

I'm first building the index.json file by using `npx make-index`. From there, I configure the filesystem and attempt to read a file using fs.readFile. I'm receiving an error that the file does not exist despite the fact that I prepopulated the filesystem with the file. Do you have any tips on how I can resolve this?

I have a minimum working example at this github repo: https://github.com/terryluan12/zen-fs-example.git

**Comment by terryluan12** [comment] 2024-06-13 21:38
The important code is in the fileSystem.ts file, which I'll copy down below:

```
import { FileSystem } from "@zenfs/core";
import { configure } from "@zenfs/core";
import fs from "@zenfs/core";
import { useEffect, useState } from "react";

import { Fetch, Overlay } from "@zenfs/core";
import { IndexedDB } from "@zenfs/dom";
import publicFileSystemIndex from "../../index.json";

const useTestFileSystem = () => {
  const [fileSys, setFileSys] = useState<FileSystem | null>(null);
  useEffect(() => {
    if (!fileSys) {
      configure({
        mounts: {
          "/": {
            backend: Overlay,
            readable: {
              backend: Fetch,
              index: publicFileSystemIndex,
            },
            writable: {
              backend: IndexedDB,
              storeName: "fs-cache",
            },
          },
        },
      });

      fs.readFile("/desktop/test", (res) => {
        console.log("READ");
        console.log("RES: " + res);
      });
      fs.readFile("public/desktop/test", (res) => {
        console.log("READ");
        console.log("RES: " + res);
      });
    }
  }, [fileSys]);
  return { fileSys };
};

export default useTestFileSystem;
```

**Comment by dr-vortex** [comment] 2024-06-13 21:56
Hi @terryluan12. `configure` is an asynchronous function so you will need to `.then` or `await` it. For example:

```ts
import { FileSystem } from "@zenfs/core";
import { configure } from "@zenfs/core";
import fs from "@zenfs/core";
import { useEffect, useState } from "react";

import { Fetch, Overlay } from "@zenfs/core";
import { IndexedDB } from "@zenfs/dom";
import publicFileSystemIndex from "../../index.json";

export default function useTestFileSystem () {
  const [fileSys, setFileSys] = useState<FileSystem | null>(null);
  useEffect(async () => {
    if (!fileSys) {
      await configure({
        mounts: {
          "/": {
            backend: Overlay,
            readable: {
              backend: Fetch,
              index: publicFileSystemIndex,
            },
            writable: {
              backend: IndexedDB,
              storeName: "fs-cache",
            },
          },
        },
      });

      fs.readFile("/desktop/test", (res) => {
        console.log("READ");
        console.log("RES: " + res);
      });
      fs.readFile("public/desktop/test", (res) => {
        console.log("READ");
        console.log("RES: " + res);
      });
    }
  }, [fileSys]);
  return { fileSys };
}
```

**Comment by dr-vortex** [comment] 2024-06-13 22:05
A quick Google search reveals that `async`/`await` is not supported in `useEffect`, so you may need to move you FS configuration outside the `useEffect` hook. You could also wrap your code that uses `fs` using `.then`.

**Comment by terryluan12** [comment] 2024-06-13 22:33
Thanks for the quick response @dr-vortex ! I believe if it's an async function, you should still be able to run it without `async`/`await` or `.then` and it would just run as a synchronous function. Irregardless, I updated my example using `.then` and removing the use of `useEffect`, and it is still giving an error below:
```
ErrnoError: EIO: Failed to parse URL from /desktop/test
    at eval (webpack-internal:///(ssr)/./node_modules/@zenfs/core/dist/backends/fetch.js:13:11)
    at async fetchFile (webpack-internal:///(ssr)/./node_modules/@zenfs/core/dist/backends/fetch.js:12:20)
    at async FetchFS.getData (webpack-internal:///(ssr)/./node_modules/@zenfs/core/dist/backends/fetch.js:102:18)
    at async FetchFS.ready (webpack-internal:///(ssr)/./node_modules/@zenfs/core/dist/backends/fetch.js:61:7)
    at async resolveMountConfig (webpack-internal:///(ssr)/./node_modules/@zenfs/core/dist/config.js:57:5)
    at async resolveMountConfig (webpack-internal:///(ssr)/./node_modules/@zenfs/core/dist/config.js:46:23)
    at async configure (webpack-internal:///(ssr)/./node_modules/@zenfs/core/dist/config.js:82:32) {
```

Currently trying to track it down, and resolve it myself, but if you have any idea on fixes, would appreciate a lead! (maybe if there's somewhere I should be configuring the base URL where it fetches from? the baseURL config option does not work lol)

**Comment by dr-vortex** [comment] 2024-06-13 22:44
I believe the option is spelled as `baseUrl`, though it should probably be changed.

**Comment by terryluan12** [comment] 2024-06-14 01:41
Hi @dr-vortex after doing some looking into the files, I've got the trace as follows (following `fs.readdir` as an example):

`fs.readdir(path)`:async.ts -> `promises.readdir(path)`:promises.ts -> `exists(path):promises.ts -> `realpath(path)`:promises.ts -> `fs.stat(resolvedPath, cred)`:locked.ts.

When it gets to locked.ts on line 143, it enter the mutex lock, and does not exit.

Could you verify the same thing happens on your end?

**Comment by terryluan12** [comment] 2024-06-14 02:45
I also noticed this while debugging. When you create the index.json file using the make-index.js script, if a file is a directory, then the `fileData` property is `[ 91, 93]` (or decoded, it's an empty array). From the IndexFS `readdirSync` file, it seems like this is not intended, right?

**Comment by dr-vortex** [comment] 2024-06-14 02:52
If I remember correctly, the listing for each directory is loaded into the `fileData` of each directory inode. I can take a closer look tomorrow.

**Comment by terryluan12** [comment] 2024-06-14 06:03
Ah, yep, you're right. It's not in the `make-index.js` file.

I think I managed to get a fix for both of the issues, as well as a possible bug. Do you mind if I make a PR?

**Comment by dr-vortex** [comment] 2024-06-14 11:35
A PR would be awesome!

**Comment by james-pre** [comment] 2024-09-07 20:37
@terryluan12,

I know we've been talking on the PR a lot, though I think most of what we've been discussing may be more related to the problem than the solution.

If you have a minute, could you please take a look at [0.17.0](https://github.com/zen-fs/core/releases/tag/v0.17.0) and see if it fixes the issue?

**Comment by terryluan12** [comment] 2024-09-07 20:42
Yep, will take a look at it, thanks James! Otherwise, am currently looking into other lock implementations to hopefully understand the issues/suggest other ways to remediate lol

**Comment by terryluan12** [comment] 2024-09-07 20:49
FYI, I'm currently getting the following error:
`Attempted import error: 'Async' is not exported from '@zenfs/core' (imported as 'Async').`.
Looking into the cause of it

**Comment by terryluan12** [comment] 2024-09-07 21:07
Turns out it's an issue with @zenfs/dom not being up to date with `0.17.0` of @zenfs/core. I'll create a PR for updating it, unless you've got a PR already underway @james-pre?

**Comment by james-pre** [comment] 2024-09-07 21:09
@terryluan12, the `Async` import problem is because index.ts was not updated with the mixin file organization. [0.17.1](https://github.com/zen-fs/core/releases/tag/v0.17.1) should fix it.

**Comment by terryluan12** [comment] 2024-09-07 21:45
Ah yep, it does, thanks James! Getting an uncaught error now haha (pasting a portion below). Trying to trace it currently.

```
Uncaught (in promise) SuppressedError: An error was suppressed during disposal.
    __disposeResources async.js:43
    fail async.js:24
    next async.js:32
    promise callback*next async.js:32
    __disposeResources async.js:40
    crossCopy async.js:189
    crossCopy async.js:172
    crossCopy async.js:172
    crossCopy async.js:172
    ready async.js:87
    resolveMountConfig config.js:45
    resolveMountConfig config.js:36
    configure config.js:77
    useTestFileSystem fileSystem.ts:26
```

**Comment by james-pre** [comment] 2024-09-07 21:47
@terryluan12 What is the error your `SuppressedError`'s `suppressed` property?

**Comment by terryluan12** [comment] 2024-09-07 21:53
The error is `Error: EINVAL: A mutation operation was attempted on a database that did not allow mutations`

**Comment by james-pre** [comment] 2024-09-07 21:55
I have never seen this error before, nor does "A mutation ..." appear in the entire ZenFS codebase - perhaps this is due to a backend API compatibility issue?

Could you please provide some more context- an error stack, what backend(s) you were using, etc?

**Comment by terryluan12** [comment] 2024-09-07 22:00
Yep! I'm using the Fetch backend from @zenfs/dom with a custom index. I'm still using the [basic example repo](https://github.com/terryluan12/zen-fs-example) I was using before if you want to see the exact setup. I just pushed the version chanage, so you should be able to recreate the error

**Comment by james-pre** [comment] 2024-09-07 22:05
This is the stack of the suppressed error (`SuppressedError.suppressed`)?

**Comment by terryluan12** [comment] 2024-09-07 22:21
Sorry about the late reply! I think I've found the stack that you're talking about? To clarify when throwing, it can be found in env.error.stack, right?

If that's the case, this is the stack:
```
abort@webpack-internal:///(app-pages-browser)/./node_modules/@zenfs/dom/dist/IndexedDB.js:46:21
[Symbol.asyncDispose]@webpack-internal:///(app-pages-browser)/./node_modules/@zenfs/core/dist/backends/store/store.js:26:20
next@webpack-internal:///(app-pages-browser)/./node_modules/@zenfs/core/dist/backends/store/fs.js:42:61
__disposeResources<@webpack-internal:///(app-pages-browser)/./node_modules/@zenfs/core/dist/backends/store/fs.js:51:16
sync@webpack-internal:///(app-pages-browser)/./node_modules/@zenfs/core/dist/backends/store/fs.js:420:48
async*sync@webpack-internal:///(app-pages-browser)/./node_modules/@zenfs/core/dist/file.js:245:23
close@webpack-internal:///(app-pages-browser)/./node_modules/@zenfs/core/dist/file.js:262:20
[Symbol.asyncDispose]@webpack-internal:///(app-pages-browser)/./node_modules/@zenfs/core/dist/file.js:546:20
next@webpack-internal:///(app-pages-browser)/./node_modules/@zenfs/core/dist/mixins/async.js:39:61
__disposeResources<@webpack-internal:///(app-pages-browser)/./node_modules/@zenfs/core/dist/mixins/async.js:48:16
crossCopy@webpack-internal:///(app-pages-browser)/./node_modules/@zenfs/core/dist/mixins/async.js:197:56
async*crossCopy@webpack-internal:///(app-pages-browser)/./node_modules/@zenfs/core/dist/mixins/async.js:180:32
async*crossCopy@webpack-internal:///(app-pages-browser)/./node_modules/@zenfs/core/dist/mixins/async.js:180:32
async*crossCopy@webpack-internal:///(app-pages-browser)/./node_modules/@zenfs/core/dist/mixins/async.js:180:32
async*ready@webpack-internal:///(app-pages-browser)/./node_modules/@zenfs/core/dist/mixins/async.js:95:28
async*resolveMountConfig@webpack-internal:///(app-pages-browser)/./node_modules/@zenfs/core/dist/config.js:56:17
async*resolveMountConfig@webpack-internal:///(app-pages-browser)/./node_modules/@zenfs/core/dist/config.js:47:29
async*configure@webpack-internal:///(app-pages-browser)/./node_modules/@zenfs/core/dist/config.js:88:38
useTestFileSystem/<@webpack-internal:///(app-pages-browser)/./src/util/fileSystem.ts:30:63
commitHookEffectListMount@webpack-internal:///(app-pages-browser)/./node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js:21102:23
commitHookPassiveMountEffects@webpack-internal:///(app-pages-browser)/./node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js:23154:32
commitPassiveMountOnFiber@webpack-internal:///(app-pages-browser)/./node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js:23259:40
recursivelyTraversePassiveMountEffects@webpack-internal:///(app-pages-browser)/./node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js:23237:32
commitPassiveMountOnFiber@webpack-internal:///(app-pages-browser)/./node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js:23370:47
recursivelyTraversePassiveMountEffects@webpack-internal:///(app-pages-browser)/./node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js:23237:32
commitPassiveMountOnFiber@webpack-internal:///(app-pages-browser)/./node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js:23370:47
recursivelyTraversePassiveMountEffects@webpack-internal:///(app-pages-browser)/./node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js:23237:32
commitPassiveMountOnFiber@webpack-internal:///(app-pages-browser)/./node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js:23370:47
recursivelyTraversePassiveMountEffects@webpack-internal:///(app-pages-browser)/./node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js:23237:32
commitPassiveMountOnFiber@webpack-internal:///(app-pages-browser)/./node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js:23256:47
recursivelyTraversePassiveMountEffects@webpack-internal:///(app-pages-browser)/./node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js:23237:32
commitPassiveMountOnFiber@webpack-internal:///(app-pages-browser)/./node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js:23370:47
recursivelyTraversePassiveMountEffects@webpack-internal:///(app-pages-browser)/./node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js:23237:32
commitPassiveMountOnFiber@webpack-internal:///(app-pages-browser)/./node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js:23256:47
recursivelyTraversePassiveMountEffects@webpack-internal:///(app-pages-browser)/./node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js:23237:32
commitPassiveMountOnFiber@webpack-internal:///(app-pages-browser)/./node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js:23370:47
recursivelyTraversePassiveMountEffects@webpack-internal:///(app-pages-browser)/./node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js:23237:32
commitPassiveMountOnFiber@webpack-internal:///(app-pages-browser)/./node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js:23256:47
recursivelyTraversePassiveMountEffects@webpack-internal:///(app-pages-browser)/./node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js:23237:32
commitPassiveMountOnFiber@webpack-internal:///(app-pages-browser)/./node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js:23256:47
recursivelyTraversePassiveMountEffects@webpack-internal:///(app-pages-browser)/./node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js:23237:32
commitPassiveMountOnFiber@webpack-internal:///(app-pages-browser)/./node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js:23256:47
recursivelyTraversePassiveMountEffects@webpack-internal:///(app-pages-browser)/./node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js:23237:32
commitPassiveMountOnFiber@webpack-internal:///(app-pages-browser)/./node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js:23370:47
recursivelyTraversePassiveMountEffects@webpack-internal:///(app-pages-browser)/./node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js:23237:32
commitPassiveMountOnFiber@webpack-internal:///(app-pages-browser)/./node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js:23256:47
recursivelyTraversePassiveMountEffects@webpack-internal:///(app-pages-browser)/./node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js:23237:32
```

**Comment by james-pre** [comment] 2024-09-07 22:28
Thanks for your patience. Looks like the error is because `IndexedDBTransaction` did not check if the underlying transaction was finished before attempting to abort/commit it. This has been fixed in [@zenfs/dom@0.2.15](https://github.com/zen-fs/dom/releases/tag/v0.2.15).

**Comment by james-pre** [comment] 2024-09-07 22:29
It looks like the error is gone if I update your test project to @zenfs/dom v0.2.15 locally.

**Comment by terryluan12** [comment] 2024-09-07 23:20
Yep! No error now! It still seems to be performing unexpectedly, since nothing is printed haha.. I'll be offline for the next 5-6 hours just an FYI, but after I can try and take a look into this. Sorry about all the bother!

**Comment by james-pre** [comment] 2024-09-09 15:22
@terryluan12, I hope you had a good weekend. Could you please let me know if everything is working well? Thanks again for your continued dedication to this project!

**Comment by terryluan12** [comment] 2024-09-09 18:47
Thanks, and you as well! It seems to be hanging  when I try to `configure` now. Specifically when it's readying, it hangs at this line:
`if (await tx.get(rootIno))`
where rootIno is 0n

**Comment by terryluan12** [comment] 2024-09-09 19:51
I've cleared my cache (and specifically my local storage), and am now facing another issue fyi. Trying to diagnose this issue currently

**Comment by terryluan12** [comment] 2024-09-09 22:40
It seems like the issue resolved itself after removing `node_modules` and reinstalling 🤷

**Comment by terryluan12** [comment] 2024-09-09 22:52
It seems like the issue is due to the program calling `MutexedFS.exists()` (in `mutex.js`), which locks the thread.

The function then calls `super.exists()` (which resolves to `Filesystem.exists()` in filesystem.js), which itself calls `MutexedFS.stat()`, which attempts to lock it again.

**Comment by terryluan12** [comment] 2024-09-09 22:55
Also, taking a look at the `addLock` function, since there's only one previous variable, wouldn't the same problem occur as earlier, if there were more than two locks?

**Comment by james-pre** [comment] 2024-09-10 14:27
@terryluan12,

> It seems like the issue is due to the program calling `MutexedFS.exists()` (in `mutex.js`), which locks the thread.
>
> The function then calls `super.exists()` (which resolves to `Filesystem.exists()` in filesystem.js), which itself calls `MutexedFS.stat()`, which attempts to lock it again.

I'll take a look.

> Also, taking a look at the `addLock` function, since there's only one `previous` variable, wouldn't the same problem occur as earlier, if there were more than two locks?

No, due to the wrapping. For instance with the A/B/C situation:
- `A()`: New lock is created (1)
- `A` begins execution
- `B()`: A new lock that wrap's `A`'s lock is created (2)
- `C()`: A new lock that wrap's `B`'s lock is created (3)
- `A` completes, unlocking the associated lock (1)
- `B` begins execution (`await this.lock(...` resolves)
- `B` completes, unlocks (2)
- `C` begins execution
- `C` completes, unlocks (3)

With the new system, a lock can be created at any time and will wrap a previous lock if it exists.

This is essentially a queue system but structured in a recursive way to simplify state management and such.

**Comment by james-pre** [comment] 2024-09-17 19:34
@terryluan12, Any updates on this? This is the last issue I have right now before looking to a potential 1.0 release.

**Comment by terryluan12** [comment] 2024-09-17 20:55
Whoops sorry! I think we were mutually waiting for responses from each other haha.

So I think have a solution to this:
> It seems like the issue is due to the program calling MutexedFS.exists() (in mutex.js), which locks the thread.
> The function then calls super.exists() (which resolves to Filesystem.exists() in filesystem.js), which itself calls MutexedFS.stat(), which attempts to lock it again.

which is basically just adding a private variable to the MutexedFS class. I'm creating a PR, but am getting an error `Uncaught (in promise) out of memory`, which I'm not convinced isn't a local error. 

Let me know your thoughts on the PR/resolution method, and if you also get this error

**Comment by terryluan12** [comment] 2024-09-17 21:25
Nevermind.. Ignore that PR. That seems to have just bypassed the lock

**Comment by terryluan12** [comment] 2024-09-17 21:50
I may be misunderstanding something, but once the FileSystem is locked, is there anything that is stopping us from using synced functions?

**Comment by terryluan12** [comment] 2024-09-17 21:51
For example, I'm thinking the following change
```
public async exists(path: string, cred: Cred): Promise<boolean> {
			using _ = await this.lock(path);
			return await super.exists(path, cred);
		}
```
to 

```
public async exists(path: string, cred: Cred): Promise<boolean> {
			using _ = await this.lock(path);
			return super.existsSync(path, cred);
		}
```

(And in fact, by this logic, this can be applied to all of the async functions)

**Comment by james-pre** [comment] 2024-09-17 22:06
If the base file system does not support sync functions (which can happen) or the async cache is disabled, then this would essentially disable the file system completely.

> It seems like the issue is due to the program calling MutexedFS.exists() (in mutex.js), which locks the thread.
> The function then calls super.exists() (which resolves to Filesystem.exists() in filesystem.js), which itself calls MutexedFS.stat(), which attempts to lock it again.

Shouldn't `super.exists()` end up calling `super.stat()`? Unless I'm forgetting, when calling a method on `super`, the `this` context inside the `super` method is `super`.

**Comment by terryluan12** [comment] 2024-09-17 22:25
It should, but I think the issue is that the only function with the same function signature is in the child class. The signature of the `stat` in the parent class is `stat(path: string, cred: Cred)`

**Comment by james-pre** [comment] 2024-09-18 16:39
@terryluan12,

Thanks for your patience. I've come up with a minimally reproducible example using Node, which results in an error:

```ts
import { configureSingle, Fetch, Overlay, fs } from '@zenfs/core';
import { readFileSync } from 'node:fs';
import { IndexedDB } from '@zenfs/dom';
import index from './index.json' with { type: 'json' };
import { createServer } from 'node:http';
import { join } from 'node:path';
import 'fake-indexeddb/auto';

createServer((req, res) => {
	const contents = readFileSync(join(import.meta.dirname, 'test', req.url));
	res.end(contents);
}).listen(12345);

await configureSingle({
	backend: Overlay,
	readable: {
		backend: Fetch,
		index,
		baseUrl: 'http://localhost:12345/',
	},
	writable: {
		backend: IndexedDB,
		storeName: 'fs-cache',
	},
});

fs.readFile('/desktop/dir/test2', { encoding: 'utf-8' }, (err, res) => {
	console.log('error', err);
	console.log(res);
});
```

Directory structure:
```ts
├── node_modules
├── index.json
├── package.json
├── package-lock.json
├── repro.ts
├── test
│   └── desktop
│       └── dir
│           ├── test
│           └── test2
└── tsconfig.json
```


I get this error, which I added in https://github.com/zen-fs/core/commit/d320b3d162ccc56c509b1a547175a0efd8ea297f:
```
@zenfs/core/dist/mixins/mutexed.js:118
                                        throw error;
                                        ^

ErrnoError: EDEADLK: Resource deadlock would occur, '/desktop/dir/test2'
    at ErrnoError.With (@zenfs/core/dist/error.js:249:16)
    at Timeout._onTimeout (@zenfs/core/dist/mixins/mutexed.js:116:31)
    at listOnTimeout (node:internal/timers:594:17)
    at process.processTimers (node:internal/timers:529:7)
    at OverlayFS.lock (@zenfs/core/dist/mixins/mutexed.js:113:18)
    at OverlayFS.exists (@zenfs/core/dist/mixins/mutexed.js:387:70)
    at exists (@zenfs/core/dist/emulation/promises.js:369:25)
    at runNextTicks (node:internal/process/task_queues:65:5)
    at process.processImmediate (node:internal/timers:459:9)
    at async _open (@zenfs/core/dist/emulation/promises.js:447:32)
    at async open (@zenfs/core/dist/emulation/promises.js:484:12)
    at async Module.readFile (@zenfs/core/dist/emulation/promises.js:491:104) {
  errno: 35,
  path: '/desktop/dir/test2',
  syscall: 'exists',
  code: 'EDEADLK'
}
```

With a minor change to trace all of the calls to `lock`, I can see 3 lock attempts on `test2`:
```
Trace: lock stat            /desktop/dir/test2
    at OverlayFS.lock (@zenfs/core/dist/mixins/mutexed.js:110:12)
    at OverlayFS.stat (@zenfs/core/dist/mixins/mutexed.js:177:69)
    at realpath (@zenfs/core/dist/emulation/promises.js:843:32)
    at async exists (@zenfs/core/dist/emulation/promises.js:368:53)
    at async _open (@zenfs/core/dist/emulation/promises.js:447:32)
    at async open (@zenfs/core/dist/emulation/promises.js:484:12)
    at async Module.readFile (@zenfs/core/dist/emulation/promises.js:491:104)
Trace: lock exists          /desktop/dir/test2
    at OverlayFS.lock (@zenfs/core/dist/mixins/mutexed.js:110:12)
    at OverlayFS.exists (@zenfs/core/dist/mixins/mutexed.js:387:70)
    at exists (@zenfs/core/dist/emulation/promises.js:369:25)
    at runNextTicks (node:internal/process/task_queues:65:5)
    at process.processImmediate (node:internal/timers:459:9)
    at async _open (@zenfs/core/dist/emulation/promises.js:447:32)
    at async open (@zenfs/core/dist/emulation/promises.js:484:12)
    at async Module.readFile (@zenfs/core/dist/emulation/promises.js:491:104)
Trace: lock stat            /desktop/dir/test2
    at OverlayFS.lock (@zenfs/core/dist/mixins/mutexed.js:110:12)
    at OverlayFS.stat (@zenfs/core/dist/mixins/mutexed.js:177:69)
    at OverlayFS.exists (@zenfs/core/dist/filesystem.js:32:24)
    at OverlayFS.exists (@zenfs/core/dist/mixins/mutexed.js:388:36)
    at runNextTicks (node:internal/process/task_queues:65:5)
    at process.processImmediate (node:internal/timers:459:9)
    at async exists (@zenfs/core/dist/emulation/promises.js:369:16)
    at async _open (@zenfs/core/dist/emulation/promises.js:447:32)
    at async open (@zenfs/core/dist/emulation/promises.js:484:12)
    at async Module.readFile (@zenfs/core/dist/emulation/promises.js:491:104)
```

It looks like the error is triggered by the second lock when checking if the file exists. A deadlock *shouldn't* occur, so this puzzles me. I will be investigating further.

Again, thank you for your help and dedication. Please let me know if you have any insight, I would appreciate a second perspective.

**Comment by terryluan12** [comment] 2024-09-18 18:59
I think the best way is maybe to turn the lock into a [recursive/re-entrant lock](https://en.wikipedia.org/wiki/Reentrant_mutex)? But I think, it would be fairly difficult, as javascript is single threaded under the hood (barring any use of Workers, which I haven't seen any in the code). 

I've been trying to think of alternate ways to this, but no luck so far

**Comment by terryluan12** [comment] 2024-09-18 19:01
I think I'm also a bit confused of the use case of the `Mutex` to be honest. Given that there is only one thread, could you not use async/await instead of `Mutexed`?

**Comment by james-pre** [comment] 2024-09-18 21:04
> I think the best way is maybe to turn the lock into a [recursive/re-entrant lock](https://en.wikipedia.org/wiki/Reentrant_mutex)? But I think it would be fairly difficult to code, as javascript is single-threaded under the hood (barring any use of Workers, which I haven't seen in the code). 

I had already attempted a recursive mutex, however it doesn't seem to have fixed the problem.

> I think I'm also a bit confused of the use case of the `Mutex` to be honest. Given that there is only one thread, could you not use async/await instead of `Mutexed`?

This is due to the callbacks API and when `.then` is used. This is more of code I just brought over when I forked from BrowserFS, I assume it was there for a good reason.

I'm working on a solution right now, but it is a complicated problem and it may take me some time.

**Comment by james-pre** [comment] 2024-09-25 19:07
@terryluan12,

Could you please let me know if [0.18.1](https://github.com/zen-fs/core/releases/tag/v0.18.1) fixes the problem? It looks like everything is working when I test it locally.

**Comment by james-pre** [comment] 2024-09-25 19:14
On second thought, you may have to wait longer due to an outage with GitHub Actions.

**Comment by terryluan12** [comment] 2024-09-27 20:58
@james-pre 
It does! Everything works properly on my end!

**Comment by terryluan12** [comment] 2024-09-27 20:59
Thank you so much for resolving the issue (and apologies I couldn't be of more help, haha)

**Comment by james-pre** [comment] 2024-09-27 21:33
Thank you for the support! I really appreciate the time you've put into this. Please let me know if you have any problems or would like to see some new features. FYI I will be looking into releasing 1.0 next week.

**Closed** 2024-09-27 21:34 UTC
Labels: bug, question
